config/routes.rb
WorkshopInscription::Application.routes.draw do
  resources :participants, only: [:new, :create]
  resources :interests, only: [:new, :create]

  get "/interests", to: redirect("/interests/new")
  get "/participants", to: redirect("/")

  root to: "participants#new"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :participants

  def full?
    self.participants.count >= self.max_participants
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_and_belongs_to_many :events

  validates :email,
    uniqueness: {message: "Email já foi cadastrado."},
    presence: {message: "Email inválido."},
    format: {with: /@.*\./, message: "Email inválido."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def new
    @participant = Participant.new
  end

  def create
    participant_params = params.require(:participant).permit(:email)
    @participant = Participant.new participant_params

    respond_to do |format|
      if @participant.save
        format.html {redirect_to new_participant_path, notice: "Você foi cadastrado com sucesso e será notificado sobre os próximos workshops!"}
      else
        @error_msg = @participant.errors.first[1]
        format.html {render "new"}
      end
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :set_event

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(email: participant_email)
    event_is_full = @event.full?
    if !event_is_full
      @participant.events << @event
    end

    respond_to do |format|
      if @participant.save
        if event_is_full
          format.html { redirect_to new_participant_path, notice: 'O evento está lotado, porém lhe avisaremos sobre os próximos.' }
        else
          InscriptionMailer.notification(@participant).deliver!
          format.html { redirect_to new_participant_path, notice: 'Parabéns! Você está confirmado para o workshop!.' }
        end
      else
        @error_msg = @participant.errors.first[1]
        format.html { render action: 'new' }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_email
      params[:participant][:email]
    end

    def set_event
      @event = Event.first || Event.create(name: "Workshop Web4Beginners", max_participants: 20)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/interests/new.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Alegreya+Sans+SC", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Varela+Round", media: "all", "data-turbolinks-track" => true %>
<% end %>

<div class="content">
<article>
	<section id="inscricao">
		<div class="control_line">
			<h2>Me avisem sobre os próximos workshops!</h2>
		</div>
    <p id="inscription_error" class="error_msg">
      <%= @error_msg %>
    </p>

		<%= form_for @participant, url: interests_path do |f| %>
			<div class="field control_line">
				<%= f.label :email %>
				<%= f.text_field :email, class: "inp", placeholder: "Informe seu e-mail..." %>
			</div>
			<div class="actions control_line">
				<button class="btn">Confirmar</button>
			</div>
      <div class="control_line">
        <%= link_to "Voltar", new_participant_path %>
      </div>
		<% end %>
	</section>
</article>

</div>

<footer>
	Este site foi desenvolvido por nós! <a href="https://github.com/xanwerneck">Alexandre Werneck</a> & <a href="https://github.com/HugoLnx/">Hugo Roque</a> & <a href="https://github.com/robertcorreas/"> Robert Corrêa </a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta property="og:image"	content="<%= asset_url "fb_opengraph.jpg" %>" />
	<title>Workshop Web4Beginners</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= yield :css %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= yield :js %>
</body>
</html>

app/views/participants/new.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Alegreya+Sans+SC", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Varela+Round", media: "all", "data-turbolinks-track" => true %>
<% end %>

<nav>
	<ul>
		<li><a href="#">Início</a></li>
		<li><a href="#equipe">Equipe</a></li>
	</ul>
</nav>

<header>
	<h1>Workshop Web4Beginners</h1>
	<p><button id="botao-inscricao" class="btn_inscricao_top">Inscrição Gratuita!</button></p>	
	<% if  flash[:notice] %>
		<p class="notice">
			<%= flash[:notice] %>
		</p>
	<% end %>
</header>

<div class="content">
<article>
	<section id="chamada" class="middle-content">
		<h2>O que vai ter por lá?</h2>
		<p>
			Neste workshop vamos mostrar como construir <strong>seu próprio site</strong>!
		</p>

		<p>
			Para isso, além de criar sua página você vai aprender como disponibilizá-la em um servidor web, tornando-a online. Usará também uma linguagem de programação (PHP) para gerar conteúdos dinâmicos neste site.
		</p>

		<p class="related-content-below">
			Com isso, no final, esperamos que você tenha:
		</p>
		<ul>
			<li>Um site simples, afinal será seu primeiro, disponível em uma URL que todos os seus amigos poderão visualizar</li>
			<li>Uma compreensão, ainda que básica, de como funciona o desenvolvimento na Web</li>
			<li>A melhor parte, um roteiro de estudo para não parar mais!</li>
		</ul>
	</section>
</article>

<div class="divider"></div>

<article>
	<section id="temprerequisitos" class="middle-content">
		<h2>Tem algum pré-requisito?</h2>
		<p>
			Muito pouco, ou quase nada, se você estiver em um curso de graduação e ter cursado a primeira disciplina sobre programação já é suficiente. Ah, não precisa saber nada de PHP também!	
		</p>
	</section>
</article>

<div class="divider"></div>

<article>
	<section id="onde" class="middle-content">
		<h2>Quando e Onde?</h2>
		<p>
			O evento ocorrerá dia <strong>19 de março (Quarta) das 8h às 12h</strong>, no 1o andar do prédio do Tecgraf, que fica no estacionamento da PUC-Rio (atrás das obras do metrô).
		</p>
		<p>
			<strong>Endereço da PUC-Rio</strong>: Rua Marquês de São Vicente, 225, Gávea - Rio de Janeiro, RJ - Brasil - 22451-900 
		</p>
	</section>
</article>

<div class="divider"></div>

<article>
<section id="equipe" class="equipe middle-content">
	<h2>A Equipe</h2>
	<ul>
		<li>
			<div class="img_membro">
				<img src="https://avatars.githubusercontent.com/u/1771461">
			</div>
			<div class="desc_membro">
				<h3>Alexandre Werneck</h3>
				<p>Desenvolvedor na PUC-RIO!</p>
			</div>
		</li>	
		<li>			
			<div class="img_membro">
				<img src="https://avatars.githubusercontent.com/u/127893">
			</div>
			<div class="desc_membro">
				<h3>Hugo Roque</h3>
				<p>Desenvolvedor na PUC-RIO!</p>
			</div>
		</li>	
		<li>
			<div class="img_membro">
				<img src="http://www.gravatar.com/avatar/ab422a99ea0947d48d18ff7fbb8df3b5?s=200">
			</div>
			<div class="desc_membro">
				<h3>Robert Corrêa</h3>
				<p>Desenvolvedor na PUC-RIO!</p>
			</div>
		</li>	
	</ul>	
</section>
</article>

<div class="divider"></div>

<article>
	<section id="inscricao">
		<div class="control_line">
			<h2>Inscrição</h2>
		</div>
    <p id="inscription_error" class="error_msg">
      <%= @error_msg %>
    </p>
		<%= form_for(@participant) do |f| %>
			<div class="field control_line">
				<%= f.label :email %>
				<%= f.text_field :email, class: "inp", placeholder: "Informe seu e-mail..." %>
			</div>
			<div class="actions control_line">
				<button class="btn">Confirmar</button>
			</div>
			<div class="control_line">
        <%= link_to "Não posso ir, mas gostaria de saber sobre os próximos workshops", new_interest_path %>
			</div>
		<% end %>
	</section>
</article>

</div>

<footer>
	Este site foi desenvolvido por nós! <a href="https://github.com/xanwerneck">Alexandre Werneck</a> & <a href="https://github.com/HugoLnx/">Hugo Roque</a> & <a href="https://github.com/robertcorreas/"> Robert Corrêa </a>
</footer>